services:
  rabbitmq:
    image: rabbitmq
    ports:
      - 5672:5672

  api:
    build: .
    ports:
      - 8000:8000
    env_file:
      - .env
  celery:
    build: .
    command: celery -A UmiShopApi worker -l INFO
