services:
  rabbitmq:
    image: rabbitmq
    network_mode: host
    # ports:
    #   - 5672:5672

  api:
    build: .
    network_mode: host
    # ports:
    #   - 8000:8000
  celery:
    build: .
    network_mode: host
    command: celery -A UmiShopApi worker -l INFO
