name: backend-challenge
on: push

env:
  DOCKER: 1

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: create env file
        run: echo "DOCKER=1" >> UmiShopApi/.env
      - name: Build the stack
        run: docker-compose -f UmiShopApi/docker-compose.yml up -d
      - name: Test
        run: docker exec -it umishopapi-api-1 python manage.py test