name: backend-challenge
on: push

env:
  DOCKER: 1

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: go in the api directory
        run: cd UmiShopApi
      - name: debug
        run: ls
      - name: Build the stack
        run: docker-compose up -d
      - name: Test
        run: docker exec -it umishopapi-api-1 python manage.py test